# Пароль для архива
password: "321"
zip: true

#Список модулей и таргетов, необходимых к запуску
need_module_name_string: Windows_ARPCache,Windows_DNSCache,Windows_IPConfig,Windows_nbtstat_NetBIOSCache,Windows_nbtstat_NetBIOSSessions,Windows_Net_Accounts,Windows_Net_File,Windows_Net_LocalGroup,Windows_Net_Session,Windows_Net_Share,Windows_Net_Start,Windows_Net_Use,Windows_Net_User,Windows_netsh_portproxy,Windows_NetStat,Windows_qwinsta_RDPSessions,Windows_RoutingTable,Windows_schtasks,Windows_SystemInfo
need_target_name_string: "!Mini_Collect"

#Удаление исполняемых файлов и шаблонов после окончания
remove_after_execute: false

#Путь до RAW-copy и других исполняемых файлов
path_to_rawcopy: ".\\bin\\rawccopy-bin\\rawccopy.exe"
path_to_all_bin: ".\\bin\\tools\\"

#Отправка результатов на веб-сервер
send_to_server: false
send_to_server_ip: "192.168.250.124"
send_to_server_url: "upload"
send_to_server_port: 8089

#Отправка результатов на Шару
send_to_own: true
send_to_own_server_ip: "185.251.90.174"
send_to_own_server_port: 5000
name_folder: "TESTUPLOAD"

#Удалять ZIP с результатами, если ZIP успешно был отправлен на сервер
remove_after_send: false